# Use root/example as user/password credentials
version: '3.1'

services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
      MYSQL_DATABASE: yourcar
    expose:
      - 3306
    ports:
      - 3306:3306
  test_database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssword
      MYSQL_DATABASE: yourcar
    expose:
      - 3307
    ports:
      - 3307:3307
